---
sudo: required
dist: xenial
addons:
  apt:
    update: true

language: python
python: "3.5"

env:
  - INVENTORY=tests/inventory; TEST_PLAY=tests/test.yml

install:
  # Setup ruby to run serverspec tests
  - ruby -v
  - gem install serverspec

  # Install Ansible
  - pip install ansible
  - ansible --version

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i $INVENTORY --syntax-check $TEST_PLAY

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i $INVENTORY --connection=local $TEST_PLAY

  # Run the role/playbook again, checking to make sure it's idempotent.
  # Allow 4 changes (for facts gethering and DB deletion test).
  - >
    ansible-playbook -i $INVENTORY --connection=local $TEST_PLAY
#    | grep -q 'changed=4.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

  # Run serverspec
  - rake spec

  # Output clickhouse-server config.xml
  - cat /etc/clickhouse-server/config.xml

  # Output clickhouse-server user.xml
  - cat /etc/clickhouse-server/users.xml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
