---
# tasks file for mediafellows.clickhouse role

# Ubuntu/Debian Installation steps:
# https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Add clickhouse apt repo key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: E0C56BD4
    state: present

- name: Install clihouse apt repo
  ansible.builtin.apt_repository:
    repo: 'deb http://repo.yandex.ru/clickhouse/deb/stable/ main/'
    state: present

- name: Install Clickhouse apt packages in specific version (if provided)
  ansible.builtin.apt:
    name:
      - "clickhouse-common-static={{ clickhouse_package_version }}"
      - "clickhouse-client={{ clickhouse_package_version }}"
      - "clickhouse-server={{ clickhouse_package_version }}"
    state: present
  when: clickhouse_package_version is defined
  notify:
    - restart clickhouse

- name: Install latest Clickhouse apt packages (unless speicific version is provided)
  ansible.builtin.apt:
    name:
      - clickhouse-client
      - clickhouse-server
    state: present
  when: clickhouse_package_version is undefined
  notify:
    - restart clickhouse

# Configuration steps:
# https://clickhouse.yandex/docs/en/operations/server_settings/settings/

- name: Ensure clickhouse config, data and log dirs exist
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: clickhouse
    group: clickhouse
    state: directory
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"

- name: Add clickhouse config
  ansible.builtin.template:
    src: config.j2
    dest: "{{ clickhouse_path_configdir }}/config.xml"
    owner: clickhouse
    group: clickhouse
  notify:
    - restart clickhouse

- name: Add clickhouse users config
  ansible.builtin.template:
    src: users.j2
    dest: "{{ clickhouse_path_configdir }}/users.xml"
    owner: clickhouse
    group: clickhouse
  notify:
    - restart clickhouse

- name: Add dictionary config from given file if provided
  ansible.builtin.template:
    src: "{{ clickhouse_dict_file }}"
    dest: "{{ clickhouse_path_configdir }}/auto_dictionary.xml"
  when: clickhouse_dict_file is defined
  notify:
    - restart clickhouse

- name: Generate dictionary config if clickhouse_dicts is defined
  ansible.builtin.template:
    src: dicts.j2
    dest: "{{ clickhouse_path_configdir }}/auto_dictionary.xml"
  when:
    - clickhouse_dicts is defined
    - clickhouse_dict_file is undefined
  notify:
    - restart clickhouse

# Get service going:

- name: Make sure clickhouse-server is started and enabled on boot
  ansible.builtin.service:
    name: clickhouse-server
    state: started
    enabled: true
  register: start_task

- name: Wait for start if service was just started
  ansible.builtin.pause:
    seconds: 2
  when: start_task.changed

# Add DBs and dictionaries (optional preparation steps):

- name: Gather list of existing databases
  ansible.builtin.shell:
    cmd: "clickhouse-client -h 127.0.0.1 -q 'show databases'"
  register: existing_databases

- name: Delete databases based on clickhouse_dbs directive
  ansible.builtin.shell:
    cmd: "clickhouse-client -h 127.0.0.1 -q 'DROP DATABASE IF EXISTS `{{ item.name }}`'"
  with_items: "{{ clickhouse_dbs }}"
  when:
    - clickhouse_dbs is defined
    - item.state is defined and item.state == 'absent' and item.name in existing_databases.stdout_lines

- name: Create databases based on clickhouse_dbs directive
  ansible.builtin.shell:
    cmd: "clickhouse-client -h 127.0.0.1 -q 'CREATE DATABASE IF NOT EXISTS `{{ item.name }}`'"
  with_items: "{{ clickhouse_dbs }}"
  when:
    - clickhouse_dbs is defined
    - (item.state is undefined or item.state == 'present') and item.name not in existing_databases.stdout_lines

- name: Run handlers
  ansible.builtin.meta: flush_handlers

