---
# tasks file for mediafellows.clickhouse role

# Ubuntu/Debian Installation steps:
# https://clickhouse.com/docs/install/debian_ubuntu

- name: Ensure tooling for install is present
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present

- name: Add Clickhouse apt signing key
  ansible.builtin.shell:
    cmd: "curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | sudo gpg --dearmor -o {{ clickhouse_apt_repo_key_location }}"
    creates: '{{ clickhouse_apt_repo_key_location }}'

- name: Add Clickhouse apt repo config
  ansible.builtin.shell:
    cmd: echo "deb [signed-by={{ clickhouse_apt_repo_key_location }}] https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
    creates: /etc/apt/sources.list.d/clickhouse.list

- name: Install Clickhouse apt packages in specific version (if provided)
  ansible.builtin.apt:
    update_cache: true
    name:
      - "clickhouse-common-static={{ clickhouse_package_version }}"
      - "clickhouse-client={{ clickhouse_package_version }}"
      - "clickhouse-server={{ clickhouse_package_version }}"
    state: present
  when: clickhouse_package_version is defined
  notify:
    - restart clickhouse

- name: Install latest Clickhouse apt packages (unless speicific version is provided)
  ansible.builtin.apt:
    update_cache: true
    name:
      - clickhouse-client
      - clickhouse-server
    state: present
  when: clickhouse_package_version is undefined
  notify:
    - restart clickhouse

# Configuration steps:
# https://clickhouse.yandex/docs/en/operations/server_settings/settings/

- name: Ensure clickhouse config, data and log dirs exist
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: clickhouse
    group: clickhouse
    state: directory
  with_items:
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_configdir }}/config.d"
    - "{{ clickhouse_path_configdir }}/users.d"
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"

- name: Add clickhouse config.d/ configs
  ansible.builtin.template:
    src: "config.d/{{ item }}.j2"
    dest: "{{ clickhouse_path_configdir }}/config.d/{{ item }}"
    owner: clickhouse
    group: clickhouse
  with_items:
    - logger.xml
    - network.xml
    - remote_hosts.xml
    - dirs.xml
  notify:
    - restart clickhouse

- name: Add clickhouse users.d/ configs
  ansible.builtin.template:
    src: "users.d/{{ item }}.j2"
    dest: "{{ clickhouse_path_configdir }}/users.d/{{ item }}"
    owner: clickhouse
    group: clickhouse
  with_items:
    - profiles.xml
    - quotas.xml
    - users.xml
  notify:
    - restart clickhouse

- name: Make sure clickhouse-server is started and enabled on boot
  ansible.builtin.service:
    name: clickhouse-server
    state: started
    enabled: true
  register: start_task

- name: Wait for start if service was just started
  ansible.builtin.pause:
    seconds: 5
  when: start_task.changed

# Info outputs:

- name: Get installed Clickhouse version (through DB query)
  ansible.builtin.shell:
    cmd: "clickhouse-client -h 127.0.0.1 --user default --password '{{ clickhouse_client_password }}' -q 'SELECT version()'"
  register: clickhouse_installed_version

- name: Output installed Clickhouse version
  ansible.builtin.debug:
    var: clickhouse_installed_version.stdout_lines

- name: Get users.xml contents
  command:
    cmd: 'cat users.xml'
    chdir: /etc/clickhouse-server/users.d
  register: command_output

- name: Output users.xml contents
  debug:
    var: command_output.stdout

# Add DBs and dictionaries (optional preparation steps):

- name: Gather list of existing databases
  ansible.builtin.shell:
    cmd: "clickhouse-client -h 127.0.0.1 --user default --password '{{ clickhouse_client_password }}' -q 'show databases'"
  register: existing_databases

- name: Delete databases based on clickhouse_dbs directive
  ansible.builtin.shell:
    cmd: "clickhouse-client -h 127.0.0.1 --user default --password '{{ clickhouse_client_password }}' -q 'DROP DATABASE IF EXISTS `{{ item.name }}`'"
  with_items: "{{ clickhouse_dbs }}"
  when:
    - clickhouse_dbs is defined
    - item.state is defined and item.state == 'absent' and item.name in existing_databases.stdout_lines

- name: Create databases based on clickhouse_dbs directive
  ansible.builtin.shell:
    cmd: "clickhouse-client -h 127.0.0.1 --user default --password '{{ clickhouse_client_password }}' -q 'CREATE DATABASE IF NOT EXISTS `{{ item.name }}`'"
  with_items: "{{ clickhouse_dbs }}"
  when:
    - clickhouse_dbs is defined
    - (item.state is undefined or item.state == 'present') and item.name not in existing_databases.stdout_lines

- name: Run handlers
  ansible.builtin.meta: flush_handlers
